module.exports = {
  Store: {
    add_new_store: '#page-header-desc-store-new_store',
    name_input: '#name_1',
    adresse_input: '#address1_1',
    postcode_input: '#postcode',
    city_input: '#city',
    shop_country_list: '#id_country',
    latitude_input: '#latitude',
    longitude_input: '#longitude',
    phone_input: '#phone',
    fax_input: '#fax',
    email_address_input: '#email',
    note_en_input: '#note_1',
    picture: '#image',
    save_button: '#store_form_submit_btn',
    active_button: '//*[@id="fieldset_0"]//div[@class="col-lg-9"]//label[@for="active_on"]',
    hours_day_input: '//*[@id="fieldset_0"]//div[@class="col-lg-7"]/input[@name="hours[%ID][1]"]',
    success_panel: '//*[@id="content"]//div[@class="alert alert-success"]',
    search_name_input: '///*[@id="table-store"]//input[@class="filter" and @name="storeFilter_a!name"]',
    search_button: '#submitFilterButtonstore',
    edit_button: '//*[@id="table-store"]//div[@class="btn-group pull-right"]/a',
    dropdown_button: '//*[@id="table-store"]//button[@class="btn btn-default dropdown-toggle"]',
    delete_button: '//*[@id="table-store"]//a[@class="delete"]',
    bulk_action_button: "#bulk_action_menu_store",
    action_button: '//*[@id="form-store"]//div[@class="btn-group bulk-actions dropup open"]//li[%ID]/a',
    store_id: '//*[@id="table-store"]/tbody/tr/td[1]',
  },
  ContactDetails: {
    shop_name: '//*[@id="conf_id_PS_SHOP_NAME"]//input[@name="PS_SHOP_NAME"]',
    shop_email: '//*[@id="conf_id_PS_SHOP_EMAIL"]//input[@name="PS_SHOP_EMAIL"]',
    shop_registration_number: '//*[@id="conf_id_PS_SHOP_DETAILS"]//textarea[@name="PS_SHOP_DETAILS"]',
    shop_adress: '//*[@id="conf_id_PS_SHOP_ADDR1"]//input[@name="PS_SHOP_ADDR1"]',
    shop_postal_code: '//*[@id="conf_id_PS_SHOP_CODE"]//input[@name="PS_SHOP_CODE"]',
    shop_city: '//*[@id="conf_id_PS_SHOP_CITY"]//input[@name="PS_SHOP_CITY"]',
    shop_phone: '//*[@id="conf_id_PS_SHOP_PHONE"]//input[@name="PS_SHOP_PHONE"]',
    shop_fax: '//*[@id="conf_id_PS_SHOP_FAX"]//input[@name="PS_SHOP_FAX"]',
    shop_country_list: '#PS_SHOP_COUNTRY_ID',
    save_button: '//*[@id="store_fieldset_contact"]//button[@type="submit"]',
    valu: '//*[@id="footer"]/div[2]/div/div[1]/div[3]/div[1]',
    store_informations_block: '//*[@id="footer"]//div[@class="block-contact col-md-4 links wrapper"]'
  }
};
